# Generated by Django 4.1.12 on 2024-02-25 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='model_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.FileField(blank=True, max_length=10000, null=True, upload_to='')),
                ('sequence_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(blank=True, choices=[('reynolds', 'reynolds'), ('ui-tei', 'ui-tei'), ('amarzguioui', 'amarzguioui')], max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('include_tm', models.BooleanField(default=True)),
                ('max_tm', models.FloatField(blank=True, null=True)),
                ('organism', models.CharField(blank=True, max_length=50, null=True)),
                ('database', models.CharField(blank=True, max_length=50, null=True)),
                ('identity', models.FloatField(blank=True, null=True)),
                ('query_cover', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
